@extends('layouts.app', ['title' => 'Panel Admin | CourseUp'])

@section('content')
<div class="space-y-8">
    <div><p class="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-700">Administrasi</p><h1 class="mt-2 text-4xl font-black">Panel Admin</h1></div>
    <section class="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Tambah Materi PDF</h2><form method="post" action="{{ route('admin.store') }}" enctype="multipart/form-data" class="mt-5 grid gap-3 md:grid-cols-2">@csrf<input name="title" required class="rounded-xl border p-3" placeholder="Judul"><input name="category" required class="rounded-xl border p-3" placeholder="Kategori"><textarea name="description" class="rounded-xl border p-3" placeholder="Deskripsi"></textarea><input name="material_file" type="file" accept="application/pdf" required class="rounded-xl border p-3"><button class="rounded-full bg-emerald-600 px-4 py-3 text-white">Tambah Materi</button></form><div class="mt-5 space-y-2">@foreach($materials as $material)<div class="flex items-center justify-between border-b py-3"><span>{{ $material->title }} <small class="text-slate-500">({{ $material->category }})</small></span><form method="post" action="{{ route('admin.materials.destroy', $material) }}">@csrf @method('delete')<button class="text-red-600">Hapus</button></form></div>@endforeach</div></section>
    <section class="grid gap-6 lg:grid-cols-2"><div class="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Kategori Quiz</h2><form method="post" action="{{ route('admin.categories.store') }}" class="mt-4 flex gap-2">@csrf<input name="category_name" required class="min-w-0 flex-1 rounded-xl border p-3" placeholder="Nama kategori"><button class="rounded-xl bg-emerald-600 px-4 text-white">Tambah</button></form>@foreach($categories as $category)<div class="flex justify-between border-b py-3"><span>{{ $category->name }} ({{ $category->questions_count }} soal)</span><form method="post" action="{{ route('admin.categories.destroy', $category) }}">@csrf @method('delete')<button class="text-red-600">Hapus</button></form></div>@endforeach</div><div class="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Tambah Soal</h2><form method="post" action="{{ route('admin.questions.store') }}" class="mt-4 grid gap-2">@csrf<select name="category_id" required class="rounded-xl border p-3"><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><textarea name="question" required class="rounded-xl border p-3" placeholder="Pertanyaan"></textarea><div class="grid gap-2 sm:grid-cols-2"><input name="option_a" required class="rounded-xl border p-3" placeholder="Opsi A"><input name="option_b" required class="rounded-xl border p-3" placeholder="Opsi B"><input name="option_c" required class="rounded-xl border p-3" placeholder="Opsi C"><input name="option_d" required class="rounded-xl border p-3" placeholder="Opsi D"></div><select name="answer_index" required class="rounded-xl border p-3"><option value="0">Jawaban A</option><option value="1">Jawaban B</option><option value="2">Jawaban C</option><option value="3">Jawaban D</option></select><textarea name="explanation" class="rounded-xl border p-3" placeholder="Penjelasan"></textarea><button class="rounded-xl bg-emerald-600 px-4 py-3 text-white">Simpan Soal</button></form></div></section>
    <section class="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Soal Quiz</h2>@foreach($questions as $question)<div class="flex items-center justify-between gap-4 border-b py-3"><span>{{ $question->question }}</span><form method="post" action="{{ route('admin.questions.destroy', $question) }}">@csrf @method('delete')<button class="text-red-600">Hapus</button></form></div>@endforeach</section>
    <section class="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Riwayat Nilai</h2>@foreach($results as $result)<div class="flex items-center justify-between border-b py-3"><span>{{ $result->user?->username ?? 'Pengguna' }}: {{ $result->score }}/{{ $result->total }} ({{ $result->percent }}%)</span><form method="post" action="{{ route('admin.results.destroy', $result) }}">@csrf @method('delete')<button class="text-red-600">Hapus</button></form></div>@endforeach</section>
    <section class="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Kontak</h2>@foreach($contacts as $contact)<div class="border-b py-3"><div class="flex justify-between gap-4"><span><b>{{ $contact->name }}</b> · {{ $contact->email }} · {{ $contact->subject }} · {{ $contact->status }}</span><span class="flex gap-3">@if($contact->status === 'unread')<form method="post" action="{{ route('admin.contacts.read', $contact) }}">@csrf @method('patch')<button class="text-emerald-700">Tandai dibaca</button></form>@endif<form method="post" action="{{ route('admin.contacts.destroy', $contact) }}">@csrf @method('delete')<button class="text-red-600">Hapus</button></form></span></div><p class="mt-1 text-sm text-slate-600">{{ $contact->message }}</p></div>@endforeach</section>
    <section class="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">FAQ</h2><form method="post" action="{{ route('admin.faqs.store') }}" class="mt-4 grid gap-2">@csrf<input name="faq_question" required class="rounded-xl border p-3" placeholder="Pertanyaan"><textarea name="faq_answer" required class="rounded-xl border p-3" placeholder="Jawaban"></textarea><button class="rounded-xl bg-emerald-600 px-4 py-3 text-white">Tambah FAQ</button></form>@foreach($faqs as $faq)<div class="border-b py-4"><p class="font-bold">{{ $faq->question }}</p><p class="mt-1 text-slate-600">{{ $faq->answer }}</p><form method="post" action="{{ route('admin.faqs.destroy', $faq) }}" class="mt-2">@csrf @method('delete')<button class="text-red-600">Hapus</button></form></div>@endforeach</section>
</div>
@endsection
